# Site settings
title:       Shawn’s C++ Corner
description: Blog & OSS highlights for my C++ journey
url:         "https://USERNAME.github.io"

# Theme
theme:       jekyll-theme-minimal
paginate:    5

# Nav
nav:
  - title: "About"
    url:   /about/
  - title: "Resume"
    url:   /resume/
  - title: "Blog"
    url:   /blog/
  - title: "OSS"
    url:   /oss/

# Markdown & syntax
markdown:    kramdown
highlighter: rouge
